:warning-caption: 💀
:important-caption: 💡

= Cheat sheet

Big UP to https://github.com/bobocode-projects/java-fundamentals-exercises[bobocode-projects] and their marvelous exercises. This is a missing part.

== Record

Records are final, immutable _or so they say_, provide `getters`, `toString`, `equals` and `hashcode`

== Declaring a record

[source,java]
----
public record FooFighter(String name, Instrument instrument, Integer yearsActive){

}
----

=== Compact constructor

[source,java]
----
import java.util.Objects;

public record FooFighter(String name, Instrument instrument, Integer yearsActive){

    public FooFighter {
        Objects.requireNonNull(name);
        Objects.requireNonNull(yearsActive);
    }

}
----

[IMPORTANT]
====

. Records are only immutable if their properties are immutable (👀 we see you object with setters, collections and all the others...), otherwise you'll have to add
 protections (copy on write, etc).
. No one told you record had to be dumb 🧠 ...

====


== Sealed interface

=== Declaring a sealed interface

[source,java]
----
import java.time.LocalDate;

public sealed interface FooFighter permits Current, Past {
    LocalDate startDate();
}
----

=== Implementing a sealed interface

Can be done with either a `final` class, a sealed

[source,java]
----
import java.time.LocalDate;

public final class Past implements FooFighter {
    public LocalDate startDate() {
        return LocalDate.of(1995, 09, 15);
    }
}
----

[source,java]
----
public sealed interface Current extends FooFighter permits Grohl, Other  {
    Boolean isTheBest();
}
----

[source,java]
----
public non-sealed interface Ovni extends FooFighter {
    String Meh();
}
----

[WARNING]
====
If you can't _specifically_ justify the need of non sealed interfaces, don't use them. If you really cannot to do without, please use them with the utmost caution. They are dynamite in your type system.
====

== Switch expression (opposed to Switch statement)

[source,java]
----


import com.grunge.FooFighter.Instrument;

Instrument instrument = ...
return switch day {
    case Instrument.GUITAR -> "Dave Grohl"
    case Instrument.DRUM -> "Dave Grohl"
    default -> {
        // Can you feel it ?
        return "DAVE GROHLLLLL";
    }
}
----

=== Pattern matching

==== In a if

[source,java]
----
if (value instanceof Person person) {
    return person.getName();
}
----


==== in a switch

[source,java]
----
return switch (value) {
    case Foo foo -> foo.foo();
    case FooFighter fighter -> fighter.fighter();
}
----

==== With a "when"

[source,java]
----
return switch (value) {
    case Foo foo -> foo.foo();
    case Fighter fighter when fighter.name().startsWith("Dave") -> "Grohl !!!!!";
}
----

==== Using deconstruction

[source,java]
----
return switch (value) {
    case Foo foo -> foo.foo();
    case Fighter(String name, Instrument instrument, _) -> "%s plays %s".formatted(name, instrument.toString()); //replace name with Dave Grohl
}
----

==== Watch out behind you, that's awful !

[WARNING]
--
[source,java]
----
public interface When {

    boolean when();
}
----

[source,java]
----
return switch (value) {
    case When when when when.when() -> when.when();
}
----
--
